openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for managing users

tags:
  - name: User
    description: Operations related to users

paths:
  /user:
    post:
      tags:
        - User
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid user data

  /user/{id}:
    get:
      tags:
        - User
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid user ID
        "404":
          description: User not found

    put:
      tags:
        - User
      summary: Update user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInput"
      responses:
        "200":
          description: User updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid user data or ID
        "404":
          description: User not found

    delete:
      tags:
        - User
      summary: Delete user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User deleted successfully
        "400":
          description: Invalid user ID
        "404":
          description: User not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "64d5f9c4b3c2e2a1d3f7e8b1"
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john@example.com"
        role:
          type: string
          example: "user"
        createdAt:
          type: string
          format: date-time
          example: "2025-08-14T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-08-14T12:00:00Z"

    UserInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        role:
          type: string
      required:
        - name
        - email
        - password
